class chat {
    constructor(io) {
        this.socket = io()
        this.box = $('#box')//messages
        this.name = $('#name')//input
        this.random = Math.floor((Math.random() * 9) + 1)
        this.messages = []
        this.colors = ['red', 'black', 'blue', 'yellow', 'purple', 'orange', 'grey', 'pink']
    }
    size() {
        let myWidth = window.innerWidth;
        if (myWidth <= 600) {
            for (let i = 0; i < 4; i++) {
                $(`.prefix${i}`).removeClass('prefix')
            }
            $(`.input_messages`).removeClass('s11').addClass('s9')
            $(`.button`).removeClass('s1').addClass('s3')
        }
    }
    materialize() {
        Materialize.toast('Bienvenido al chat de Andrés.', 4000)
    }
    sendMessage() {
        this.socket.on('message', data => {
            this.messages.push(data)
            //sends data to code html
            let html = ''
            for (let i = 0; i < this.messages.length; i++) {
                html += `<li style='color: ${this.messages[i].color};'> ${this.messages[i].username ? this.messages[i].username : 'Server'}: </li>`
                html += `<li>${this.messages[i].message}</li><br/>`
            }
            //scroll down
            this.animate()
            //send html code generated by the for
            $('.messages').html(html)
        })
    }
    animate() {
        $('#content').animate({
            scrollTop: $('#content')[0].scrollHeight
        }, 100)
    }
    buttonClick() {
        if (this.name.val() != '') {
            //$('#name').attr('disabled', 'disabled')
            //hide textbox
            $('.namebox').hide(1000)
            this.socket.emit('send', {
                message: this.box.val(),
                username: this.name.val(),
                color: this.colors[this.random]
            })
            this.box.val('')
        }
    }
    main() {
        this.size()
        this.materialize()
        this.sendMessage()
        $('#send').click(() => {
            this.buttonClick()
        })
        $('#box').keypress((e) => {
            if (e.which == 13) {
                this.buttonClick()
            }
        })
    }
}

$(document).ready(() => {
    const main = new chat(io)
    main.main()
})

